### ISSUE TITLE
Installing Madeline2 

### ISSUE THREAD

**Issue by joreynajr** [frazer-lab/cluster#137]
I'm trying to install Madeline2 but I keep running into this issue after I try Step 3 in the installation steps for Madeline2 (found at https://madeline.med.umich.edu/madeline/building.php). 

.
.
.
[  0%] Built target api-docs
[  2%] Built target unzip
[  8%] Built target translations
[ 10%] Building CXX object src/CMakeFiles/madeline2.dir/Pedigree.cpp.o
/frazer01/home/joreyna/software/Madeline_2.0_PDE/src/Pedigree.cpp: In member function 'void Pedigree::reportUnconnectedIndividuals()':
/frazer01/home/joreyna/software/Madeline_2.0_PDE/src/Pedigree.cpp:2861: error: 'nullptr' was not declared in this scope
make[2]: **\* [src/CMakeFiles/madeline2.dir/Pedigree.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/madeline2.dir/all] Error 2
make: **\* [all] Error 2

There are some prerequisites which seem like we have them installed either as a module or system installed program (cmake (module), openssl (system), curl (system), libXML2 is the only one I'm unsure about). 

Right now I'm trying to install in /frazer01/home/joreyna/software/Madeline_2.0_PDE

**Comment by tatarsky** [comment]
I'll take a look. That doesn't match any of my "things that crop up" list ;)

Sounds like a code bug to me offhand.

**Comment by joreynajr** [comment]
Thanks! Hopefully it's not too complicated.

**Comment by tatarsky** [comment]
Appears to be instead a C++ language compat bug. It does work with the Gcc/G++ 4.8.5 we have with a module. At least it compiles.

Try this and there are probably easier ways but this seemed to get the job done.

```
$ cmake -DCMAKE_C_COMPILER=/frazer01/software/gcc-4.8.5/bin/gcc -DCMAKE_CXX_COMPILER=/frazer01/software/gcc-4.8.5/bin/c++
$ make

(wait)
$ src/madeline2 
âââââââââââââââââââââââââââââââ
â Welcome to Madeline 2.0 PDE â
âââââââââââââââââââââââââââââââ
Usage: madeline2 [option]... [file]...

If input file is remote, specify the file
name starting with 'http://' or 'https://'.
To retrieve the data from a mysql database use
'mysql://[host:port/]username:passwd@database:table'

(etc)

```

**Comment by joreynajr** [comment]
Awesome! That worked out! Closing the issue.
