### ISSUE TITLE
Install bioconductor packages

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#44]
I'm trying to install some bioconductor packages into the R installation available using `module load R/3.1.1` and running into some compilation errors. As an example, try launching R and running `source("http://bioconductor.org/biocLite.R") ; biocLite("DEXSeq")`. I tried loading the gcc module before launching R but that didn't fix the problem. In total I'm trying to install DEXSeq, DESeq2, Gviz, goseq, org.Hs.eg.db, and qvalue from bioconductor.

**Comment by tatarsky** [comment]
OK. I'll take a look in a bit today. I have a dim memory of some version issue with R and something that forced me into 3.2.X recently but I don't recall what.  I get this BTW when I do the source:

```
source("http://bioconductor.org/biocLite.R")
Bioconductor version 3.0 (BiocInstaller 1.16.5), ?biocLite for help
A new version of Bioconductor is available after installing the most recent
  version of R; see http://bioconductor.org/install
```

**Comment by tatarsky** [comment]
Ah, and it was because of this I updated at another location. Not saying its your problem, but be aware:

```
The current release of Bioconductor is version 3.2; it works with R version 3.2.2. 
Users of older R and Bioconductor versions must update their installation to take advantage of new features.
```

**Comment by cdeboever3** [comment]
Ok I'll try with 3.2.2.

**Comment by cdeboever3** [comment]
Installing with 3.2.2 worked. I'll make a module and make that the new default R. Thanks
